version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: hardening-scoreboard-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hardening_scoreboard
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/database/migrations:/docker-entrypoint-initdb.d
    networks:
      - hardening-network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: hardening-scoreboard-backend
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/hardening_scoreboard
      NODE_ENV: production
    depends_on:
      - postgres
    networks:
      - hardening-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: hardening-scoreboard-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - hardening-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  hardening-network:
    driver: bridge